#
# N.B.: docker compose must be invoked from the project root directory:
#
# docker compose -f path/to/compose.yaml up --exit-code-from cantaloupe
#
services:
  cantaloupe:
    platform: linux/amd64
    build:
      context: ../../
      dockerfile: $PWD/docker/Linux-JDK25/Dockerfile
  rustfs-server:
    image: rustfs/rustfs
    environment:
      RUSTFS_ACCESS_KEY: RustfsUser
      RUSTFS_SECRET_KEY: OpenSesame
    ports: ["9000:9000/tcp"]
  redis:
    image: redis:alpine
    hostname: redis
