#
# N.B.: docker compose must be invoked from the project root directory:
#
# docker compose -f path/to/compose.yaml up --exit-code-from cantaloupe
#
services:
  cantaloupe:
    build:
      context: ../../
      dockerfile: $PWD/docker/Linux-JDK17/Dockerfile
  minio:
    image: minio/minio
    environment:
      MINIO_ACCESS_KEY: MinioUser
      MINIO_SECRET_KEY: OpenSesame
    hostname: minio
    command: server /data
  redis:
    image: redis:alpine
    hostname: redis
