s3.service = seaweedfs
s3.endpoint = http://seaweedfs:8333
s3.region =
s3.access_key_id = SeaweedUser
s3.secret_key = OpenSesame
s3.bucket = test.cantaloupe.library.illinois.edu

# Azurite (Azure Storage emulator) well-known development account
azurestorage.account_name = devstoreaccount1
azurestorage.account_key = Eby8vdM02xNOcqFlqUwJPLlmEtlCDXJ1OUzFT50uSRZ6IFsuFq2UVErCz4I6tq/K1SZFPTOtr/KBHBeksoGMGw==
azurestorage.container = cantaloupe-test
azurestorage.endpoint = http://azurite:10000/devstoreaccount1

redis.host = redis
redis.port = 6379
redis.ssl = false
redis.password =
redis.database = 0
