#
# N.B.: docker-compose must be invoked from the project root directory:
#
# docker compose -f path/to/compose.yaml up --exit-code-from cantaloupe
#
services:
  cantaloupe:
    build:
      context: ../../
<<<<<<<< HEAD:docker/Windows-JDK18/docker-compose.yml
      dockerfile: docker/Windows-JDK18/Dockerfile
  minio:
    build:
      context: ../../
      dockerfile: docker/Windows-JDK18/Dockerfile-minio
========
      dockerfile: docker/Windows-JDK21/Dockerfile
  minio:
    build:
      context: ../../
      dockerfile: docker/Windows-JDK21/Dockerfile-minio
>>>>>>>> develop:docker/Windows-JDK21/compose.yaml
    environment:
      MINIO_ACCESS_KEY: MinioUser
      MINIO_SECRET_KEY: OpenSesame
    hostname: minio
