name: CI
on:
  push:
    branches:
      - develop
      - release/*
  pull_request:
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, ubuntu-22.04]
        java: [jdk21, jdk25, jdk26, graalvm]
      fail-fast: false
    steps:
      - name: Check out the repository
        uses: actions/checkout@v6
      - name: Test in Linux JDK 26 (non-LTS)
        if: matrix.os == 'ubuntu-latest' && matrix.java == 'jdk26'
        run: docker compose -f docker/Linux-JDK26/compose.yaml up --build --exit-code-from cantaloupe
      - name: Test in Linux JDK 25 (LTS)
        if: matrix.os == 'ubuntu-latest' && matrix.java == 'jdk25'
        run: docker compose -f docker/Linux-JDK25/compose.yaml up --build --exit-code-from cantaloupe
      - name: Test in Linux JDK 21 (LTS)
        if: matrix.os == 'ubuntu-latest' && matrix.java == 'jdk21'
        run: docker compose -f docker/Linux-JDK21/compose.yaml up --build --exit-code-from cantaloupe
      - name: Test in Linux GraalVM
        if: matrix.os == 'ubuntu-latest' && matrix.java == 'graalvm'
        run: docker compose -f docker/Linux-GraalVM-JDK21/compose.yaml up --build --exit-code-from cantaloupe
      # Only test one java version on Jammy
      - name: Test in Ubuntu Jammy
        if: matrix.os == 'ubuntu-22.04' && matrix.java == 'jdk21'
        run: docker compose -f docker/ubuntu/jammy/compose.yaml up --build --exit-code-from cantaloupe
      - name: Test in Windows JDK 25 (LTS)
        if: matrix.os == 'windows-latest' && matrix.java == 'jdk25'
        run: docker compose -f docker/Windows-JDK25/compose.yaml up --build --exit-code-from cantaloupe
      - name: Test in Windows JDK 21 (LTS)
        if: matrix.os == 'windows-latest' && matrix.java == 'jdk21'
        run: docker compose -f docker/Windows-JDK21/compose.yaml up --build --exit-code-from cantaloupe
      # TODO: Windows+GraalVM
