on:
  push:
    tags:
      - "v*"
name: Upload Release Asset
jobs:
  build:
    name: Upload Release Asset
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-java@v5
        with:
          distribution: "temurin"
          java-version: "21"
          java-package: jdk
          architecture: x64
      - name: Checkout Code
        uses: actions/checkout@v6
      - name: Build Project
        # we assume that the tests for this tag have already passed
        # (otherwise the tag wouldn't have been pushed)
        run: mvn clean package -DskipTests
      - name: Create Release and Upload Asset
        uses: softprops/action-gh-release@v3
        with:
          files: target/cantaloupe-*.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
